name: Compiler Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM and Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Build compiler
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Cache compiler build
        uses: actions/cache/save@v4
        with:
          path: target/x86_64-unknown-linux-gnu/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  lexer-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: target/x86_64-unknown-linux-gnu/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run lexer tests
        run: |
          cd test 
          python3 main.py --stage lexer
        env:
          BRITTEN_PATH: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/britten

  parser-tests:
    needs: lexer-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: target/x86_64-unknown-linux-gnu/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run parser tests
        run: |
          cd test 
          python3 main.py --stage parser
        env:
          BRITTEN_PATH: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/britten

  llvm-tests:
    needs: parser-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: target/x86_64-unknown-linux-gnu/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run LLVM tests
        run: |
          cd test 
          python3 main.py --stage llvm
        env:
          BRITTEN_PATH: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/britten

  asm-tests:
    needs: llvm-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: target/x86_64-unknown-linux-gnu/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run assembly tests
        run: |
          cd test 
          python3 main.py --stage asm
        env:
          BRITTEN_PATH: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/britten

  full-compiler-tests:
    needs: asm-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: target/x86_64-unknown-linux-gnu/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run full compilation tests
        run: |
          cd test 
          python3 main.py --stage full
        env:
          BRITTEN_PATH: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/britten